// Arenet - Homelab-friendly reverse proxy with integrated security
// Copyright (C) 2026  Ludovic Ramos
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see https://www.gnu.org/licenses/.

package storage

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"time"

	bolt "go.etcd.io/bbolt"
)

// Step AL.1.b — alerting Channel CRUD on BoltDB.
//
// Layout: bucketAlertingChannels keyed by Channel.ID (UUID
// v4, generated by the API CRUD layer before Create). The
// operator-facing Channel.Name is unique-checked at create
// + update time via bucket scan — homelab volumes are
// small (operator typically has 1-3 channels) so the O(N)
// scan stays trivial vs the complexity of an inverse index
// bucket.

// CreateAlertChannel persists a new channel. Returns
// ErrConflict if Channel.Name collides with any existing
// channel. The caller is responsible for setting
// Channel.ID (UUID v4) before calling — the storage layer
// does NOT auto-generate it because the API layer needs
// the ID for the audit event row that fires alongside the
// create.
func (s *Store) CreateAlertChannel(ctx context.Context, c Channel) (Channel, error) {
	ctx, cancel := withTimeout(ctx)
	defer cancel()

	if err := c.validate(); err != nil {
		return Channel{}, err
	}
	if c.ID == "" {
		return Channel{}, errors.New("alerting_channel: id must not be empty (caller supplies the UUID)")
	}

	now := time.Now().UTC()
	c.CreatedAt = now
	c.UpdatedAt = now

	err := s.db.Update(func(tx *bolt.Tx) error {
		if err := ctx.Err(); err != nil {
			return err
		}
		b := tx.Bucket([]byte(bucketAlertingChannels))
		// Name uniqueness scan.
		var conflict bool
		_ = b.ForEach(func(_, v []byte) error {
			var existing Channel
			if err := json.Unmarshal(v, &existing); err != nil {
				return nil
			}
			if existing.Name == c.Name {
				conflict = true
			}
			return nil
		})
		if conflict {
			return ErrConflict
		}
		// ID collision (operator regenerated UUID by mistake) →
		// also ErrConflict, distinct cause but same observable
		// for the API caller.
		if existing := b.Get([]byte(c.ID)); existing != nil {
			return ErrConflict
		}
		buf, err := json.Marshal(c)
		if err != nil {
			return fmt.Errorf("marshal alerting_channel: %w", err)
		}
		return b.Put([]byte(c.ID), buf)
	})
	if err != nil {
		return Channel{}, err
	}
	return c, nil
}

// GetAlertChannel returns the channel keyed by ID, or
// ErrNotFound.
func (s *Store) GetAlertChannel(ctx context.Context, id string) (Channel, error) {
	ctx, cancel := withTimeout(ctx)
	defer cancel()

	if id == "" {
		return Channel{}, errors.New("alerting_channel: id must not be empty")
	}
	var out Channel
	err := s.db.View(func(tx *bolt.Tx) error {
		if err := ctx.Err(); err != nil {
			return err
		}
		raw := tx.Bucket([]byte(bucketAlertingChannels)).Get([]byte(id))
		if raw == nil {
			return ErrNotFound
		}
		return json.Unmarshal(raw, &out)
	})
	if err != nil {
		return Channel{}, err
	}
	return out, nil
}

// ListAlertChannels returns every channel, sorted by
// CreatedAt ascending. Operator-side ordering — the UI's
// "channels list" reads in stable creation order so a new
// channel always appears at the bottom.
func (s *Store) ListAlertChannels(ctx context.Context) ([]Channel, error) {
	ctx, cancel := withTimeout(ctx)
	defer cancel()

	var out []Channel
	err := s.db.View(func(tx *bolt.Tx) error {
		if err := ctx.Err(); err != nil {
			return err
		}
		return tx.Bucket([]byte(bucketAlertingChannels)).ForEach(func(_, v []byte) error {
			var c Channel
			if err := json.Unmarshal(v, &c); err != nil {
				return fmt.Errorf("unmarshal alerting_channel row: %w", err)
			}
			out = append(out, c)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(out, func(i, j int) bool {
		return out[i].CreatedAt.Before(out[j].CreatedAt)
	})
	return out, nil
}

// UpdateAlertChannel persists an existing channel. The
// caller supplies the FULL Channel shape (preserve-on-omit
// semantics live at the API layer per Lesson 8). Returns
// ErrNotFound if the ID does not exist, ErrConflict if the
// Name would collide with a DIFFERENT existing channel.
// CreatedAt is preserved from the stored row; UpdatedAt
// is overwritten with time.Now().
func (s *Store) UpdateAlertChannel(ctx context.Context, c Channel) (Channel, error) {
	ctx, cancel := withTimeout(ctx)
	defer cancel()

	if err := c.validate(); err != nil {
		return Channel{}, err
	}
	if c.ID == "" {
		return Channel{}, errors.New("alerting_channel: id must not be empty")
	}

	now := time.Now().UTC()
	c.UpdatedAt = now

	err := s.db.Update(func(tx *bolt.Tx) error {
		if err := ctx.Err(); err != nil {
			return err
		}
		b := tx.Bucket([]byte(bucketAlertingChannels))
		raw := b.Get([]byte(c.ID))
		if raw == nil {
			return ErrNotFound
		}
		var existing Channel
		if err := json.Unmarshal(raw, &existing); err != nil {
			return fmt.Errorf("unmarshal stored alerting_channel: %w", err)
		}
		c.CreatedAt = existing.CreatedAt

		// Name uniqueness scan, excluding the current row.
		var conflict bool
		_ = b.ForEach(func(k, v []byte) error {
			if string(k) == c.ID {
				return nil
			}
			var other Channel
			if err := json.Unmarshal(v, &other); err != nil {
				return nil
			}
			if other.Name == c.Name {
				conflict = true
			}
			return nil
		})
		if conflict {
			return ErrConflict
		}

		buf, err := json.Marshal(c)
		if err != nil {
			return fmt.Errorf("marshal alerting_channel: %w", err)
		}
		return b.Put([]byte(c.ID), buf)
	})
	if err != nil {
		return Channel{}, err
	}
	return c, nil
}

// DeleteAlertChannel removes the row keyed by ID. Returns
// ErrNotFound if the ID does not exist. The audit row is
// the caller's responsibility (the API layer reads the
// stored Channel for BeforeJSON before calling Delete so
// the audit captures the deleted shape).
func (s *Store) DeleteAlertChannel(ctx context.Context, id string) error {
	ctx, cancel := withTimeout(ctx)
	defer cancel()

	if id == "" {
		return errors.New("alerting_channel: id must not be empty")
	}
	return s.db.Update(func(tx *bolt.Tx) error {
		if err := ctx.Err(); err != nil {
			return err
		}
		b := tx.Bucket([]byte(bucketAlertingChannels))
		if existing := b.Get([]byte(id)); existing == nil {
			return ErrNotFound
		}
		return b.Delete([]byte(id))
	})
}

// MarkAlertChannelSendResult updates the LastSentAt /
// LastError / LastErrorAt fields after a send attempt.
// Called by the dispatcher layer (post-send) and by the
// CRUD /test endpoint. Idempotent: a re-call with the same
// outcome just refreshes the timestamps.
//
// On success (sendErr == nil): LastSentAt = now, LastError
// = "", LastErrorAt = nil.
// On failure: LastError = sendErr.Error(), LastErrorAt =
// now. LastSentAt is left untouched so the operator can
// see "last successful send" + "most recent failure"
// side-by-side.
func (s *Store) MarkAlertChannelSendResult(ctx context.Context, id string, sendErr error) error {
	ctx, cancel := withTimeout(ctx)
	defer cancel()

	if id == "" {
		return errors.New("alerting_channel: id must not be empty")
	}
	now := time.Now().UTC()
	return s.db.Update(func(tx *bolt.Tx) error {
		if err := ctx.Err(); err != nil {
			return err
		}
		b := tx.Bucket([]byte(bucketAlertingChannels))
		raw := b.Get([]byte(id))
		if raw == nil {
			return ErrNotFound
		}
		var c Channel
		if err := json.Unmarshal(raw, &c); err != nil {
			return fmt.Errorf("unmarshal alerting_channel: %w", err)
		}
		if sendErr == nil {
			c.LastSentAt = &now
			c.LastError = ""
			c.LastErrorAt = nil
		} else {
			c.LastError = sendErr.Error()
			c.LastErrorAt = &now
		}
		c.UpdatedAt = now
		buf, err := json.Marshal(c)
		if err != nil {
			return fmt.Errorf("marshal alerting_channel: %w", err)
		}
		return b.Put([]byte(id), buf)
	})
}
