// Arenet - Homelab-friendly reverse proxy with integrated security
// Copyright (C) 2026  Ludovic Ramos
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see https://www.gnu.org/licenses/.

package api

import (
	"context"
	"encoding/json"
	"log/slog"
	"net/http"

	"github.com/barto95100/arenet/internal/audit"
	"github.com/barto95100/arenet/internal/auth"
)

// appendAudit emits an audit event with context enrichment (spec §5.9).
//
// The caller fills evt.Action, evt.TargetType, evt.TargetID,
// evt.BeforeJSON, evt.AfterJSON, evt.Message. The helper fills:
//   - evt.ActorUserID and evt.ActorUsernameSnapshot from request context
//   - evt.IP from request context (X-Forwarded-For aware, see spec §5.4)
//   - evt.UserAgent from r.Header
//
// ID and Timestamp are generated by audit.Store.Append via uuid.NewV7
// (overwriting any caller-supplied values).
//
// Best-effort: a failure to persist the event logs at Warn level but
// does NOT affect the HTTP response. Per decision D2, the business
// operation has already succeeded by this point; the audit emission
// is observability, not request flow.
//
// SECURITY: this helper does NOT log evt.Message even on failure,
// because Message may contain free text from the user (e.g., the
// login_failure reason includes the attempted username snapshot).
// Logging Message would risk leaking sensitive content to slog if a
// caller is sloppy about what they put there. Only Action and
// TargetID are logged, both of which are non-sensitive enum/UUID
// values.
func (h *Handler) appendAudit(r *http.Request, evt audit.Event) {
	ctx := r.Context()
	evt.ActorUserID = auth.UserIDFromContext(ctx)
	evt.ActorUsernameSnapshot = auth.UsernameFromContext(ctx)
	evt.IP = auth.ClientIPFromContext(ctx)
	evt.UserAgent = r.UserAgent()

	if err := h.audit.Append(ctx, evt); err != nil {
		h.logger.Warn("audit append failed",
			slog.String("err", err.Error()),
			slog.String("action", evt.Action),
			slog.String("target_id", evt.TargetID),
		)
	}
}

// appendAuditBackground emits an audit event when no *http.Request is
// available (e.g., the deferred HIBP re-check at login — spec §7.6).
//
// The caller supplies the actor's user ID directly; the rest of the
// context-derived fields (IP, UserAgent) are left empty because the
// event is not tied to a live HTTP request anymore. The event still
// includes Action, TargetType, TargetID, Message as filled by the
// caller.
//
// The audit.Append call uses the supplied context; callers are
// expected to pass a fresh context.Background()-derived value (the
// HIBP recheck goroutine cannot use the original request ctx because
// it has been cancelled by the time this fires).
//
// Best-effort, identical observability/logging policy to appendAudit.
func (h *Handler) appendAuditBackground(ctx context.Context, actorUserID string, evt audit.Event) {
	evt.ActorUserID = actorUserID
	// ActorUsernameSnapshot, IP, UserAgent intentionally left empty:
	// no live request context, no client metadata to record.

	if err := h.audit.Append(ctx, evt); err != nil {
		h.logger.Warn("audit append (background) failed",
			slog.String("err", err.Error()),
			slog.String("action", evt.Action),
			slog.String("target_id", evt.TargetID),
		)
	}
}

// mustMarshalForAudit serializes a value to JSON for inclusion in
// audit event BeforeJSON / AfterJSON fields. Despite the "must"
// prefix, it does NOT panic: it returns nil on marshal error so the
// event is still emitted, just without the diff.
//
// The "must" naming follows the Go idiom for "best-effort with
// sensible default", contrasting with regexp.MustCompile (which
// panics). The intent here is to keep audit emission unstoppable:
// a borked marshal must not abort the operator-visible record.
//
// SECURITY: callers MUST strip sensitive fields (PasswordHash on
// User, session tokens, API keys, etc.) BEFORE passing the value
// here. This function performs NO sanitization — it serializes
// whatever you give it. Spec §3.4 and decision D3 forbid such
// content in BeforeJSON/AfterJSON.
func mustMarshalForAudit(v any) json.RawMessage {
	raw, err := json.Marshal(v)
	if err != nil {
		return nil
	}
	return raw
}
