// Arenet - Homelab-friendly reverse proxy with integrated security
// Copyright (C) 2026  Ludovic Ramos
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see https://www.gnu.org/licenses/.

package api

import (
	"context"
	"encoding/json"
	"log/slog"
	"net/http"

	"time"

	"github.com/barto95100/arenet/internal/audit"
	"github.com/barto95100/arenet/internal/auth"
	"github.com/barto95100/arenet/internal/observability"
)

// authFailureKind maps audit Action constants to AuthEvent
// kinds for the Step V.2 sink fan-out. Returns the kind +
// true when the action is an auth failure that should reach
// the auth_event sink; returns (_, false) for every other
// audit action so the fan-out branch is a no-op for non-auth
// audit writes (route changes, settings edits, etc.).
//
// The map is the single point of truth for which audit
// actions cross into the auth_event stream. Add a new entry
// here when a new auth-failure audit action ships; no other
// site needs to know.
func authFailureKind(action string) (observability.AuthEventKind, bool) {
	switch action {
	case audit.ActionLoginFailure:
		return observability.AuthEventKindLoginFailure, true
	case audit.ActionOIDCLoginRejected, audit.ActionOIDCCallbackInvalid:
		return observability.AuthEventKindOIDCCallbackRejected, true
	default:
		return 0, false
	}
}

// appendAudit emits an audit event with context enrichment (spec §5.9).
//
// The caller fills evt.Action, evt.TargetType, evt.TargetID,
// evt.BeforeJSON, evt.AfterJSON, evt.Message. The helper fills the
// following fields ONLY IF the caller did not pre-populate them:
//   - evt.ActorUserID and evt.ActorUsernameSnapshot from request context
//   - evt.IP from request context (X-Forwarded-For aware, see spec §5.4)
//   - evt.UserAgent from r.Header
//
// CONTRACT DIVERGENCE from spec §5.9 (which says "helper fills"):
// no-auth endpoints like /login and /setup run BEFORE the soft-auth
// middleware that would otherwise populate the auth context keys.
// On those endpoints the handler manually pre-populates
// ActorUserID and ActorUsernameSnapshot (e.g., login on success
// sets them from the just-authenticated User; login on failure sets
// ActorUsernameSnapshot to the attempted username). The
// "fill only if empty" rule preserves those caller values rather
// than overwriting them with the empty context values.
//
// ID and Timestamp are generated by audit.Store.Append via uuid.NewV7
// (overwriting any caller-supplied values).
//
// Best-effort: a failure to persist the event logs at Warn level but
// does NOT affect the HTTP response. Per decision D2, the business
// operation has already succeeded by this point; the audit emission
// is observability, not request flow.
//
// SECURITY: this helper does NOT log evt.Message even on failure,
// because Message may contain free text from the user (e.g., the
// login_failure reason includes the attempted username snapshot).
// Logging Message would risk leaking sensitive content to slog if a
// caller is sloppy about what they put there. Only Action and
// TargetID are logged, both of which are non-sensitive enum/UUID
// values.
func (h *Handler) appendAudit(r *http.Request, evt audit.Event) {
	ctx := r.Context()
	// Fill from context ONLY when the caller did not pre-populate the
	// field. On no-auth endpoints (e.g. /login), the auth context keys
	// are unset; the handler passes ActorUsernameSnapshot explicitly so
	// the login_failure event carries the attempted username. The
	// pre-existing pattern (handler fills success path, context fills
	// soft/hard-auth paths) is preserved.
	if evt.ActorUserID == "" {
		evt.ActorUserID = auth.UserIDFromContext(ctx)
	}
	if evt.ActorUsernameSnapshot == "" {
		evt.ActorUsernameSnapshot = auth.UsernameFromContext(ctx)
	}
	if evt.IP == "" {
		evt.IP = auth.ClientIPFromContext(ctx)
	}
	if evt.UserAgent == "" {
		evt.UserAgent = r.UserAgent()
	}

	if err := h.audit.Append(ctx, evt); err != nil {
		h.logger.Warn("audit append failed",
			slog.String("err", err.Error()),
			slog.String("action", evt.Action),
			slog.String("target_id", evt.TargetID),
		)
	}

	// Step V.2: parallel fan-out to the auth_event sink for
	// auth-failure actions. Order is audit-first / sink-second
	// per spec §3.6 ("a real-time fan-out parallel to it, not
	// a replacement"). Submit is non-blocking + nil-safe so a
	// degraded sink never stalls the request goroutine. Only
	// auth-failure actions reach the sink — settings edits,
	// route changes, etc. flow through audit alone.
	if h.authSink != nil {
		if kind, ok := authFailureKind(evt.Action); ok {
			h.authSink.Submit(observability.AuthEvent{
				Ts:       time.Now().UTC(),
				Kind:     kind,
				SrcIP:    evt.IP,
				Username: evt.ActorUsernameSnapshot,
				Path:     r.URL.Path,
				Details:  evt.Message,
			})
		}
	}
}

// appendAuditBackground emits an audit event when no *http.Request is
// available (e.g., the deferred HIBP re-check at login — spec §7.6).
//
// The caller supplies the actor's user ID directly; the rest of the
// context-derived fields (IP, UserAgent) are left empty because the
// event is not tied to a live HTTP request anymore. The event still
// includes Action, TargetType, TargetID, Message as filled by the
// caller.
//
// The audit.Append call uses the supplied context; callers are
// expected to pass a fresh context.Background()-derived value (the
// HIBP recheck goroutine cannot use the original request ctx because
// it has been cancelled by the time this fires).
//
// Best-effort, identical observability/logging policy to appendAudit.
func (h *Handler) appendAuditBackground(ctx context.Context, actorUserID string, evt audit.Event) {
	evt.ActorUserID = actorUserID
	// ActorUsernameSnapshot, IP, UserAgent intentionally left empty:
	// no live request context, no client metadata to record.

	if err := h.audit.Append(ctx, evt); err != nil {
		h.logger.Warn("audit append (background) failed",
			slog.String("err", err.Error()),
			slog.String("action", evt.Action),
			slog.String("target_id", evt.TargetID),
		)
	}
}

// mustMarshalForAudit serializes a value to JSON for inclusion in
// audit event BeforeJSON / AfterJSON fields. Despite the "must"
// prefix, it does NOT panic: it returns nil on marshal error so the
// event is still emitted, just without the diff.
//
// The "must" naming follows the Go idiom for "best-effort with
// sensible default", contrasting with regexp.MustCompile (which
// panics). The intent here is to keep audit emission unstoppable:
// a borked marshal must not abort the operator-visible record.
//
// SECURITY: callers MUST strip sensitive fields (PasswordHash on
// User, session tokens, API keys, etc.) BEFORE passing the value
// here. This function performs NO sanitization — it serializes
// whatever you give it. Spec §3.4 and decision D3 forbid such
// content in BeforeJSON/AfterJSON.
func mustMarshalForAudit(v any) json.RawMessage {
	raw, err := json.Marshal(v)
	if err != nil {
		return nil
	}
	return raw
}
