// Arenet - Homelab-friendly reverse proxy with integrated security
// Copyright (C) 2026  Ludovic Ramos
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see https://www.gnu.org/licenses/.

package api

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/hex"
	"sync"
)

// SetupTokenByteLen is the entropy of the setup token: 32 bytes from
// crypto/rand encoded as 64 hex characters. Spec §4.2 + decision Q2.
const SetupTokenByteLen = 32

// SetupTokenHolder owns the in-memory setup token that gates the
// first-boot admin creation flow. The token is generated by
// cmd/arenet at startup when the users bucket is empty and logged
// to slog at Info level. It is invalidated server-side immediately
// after a successful /auth/setup call (spec §4.2 "preventing replay").
//
// SetupTokenHolder is safe for concurrent use.
type SetupTokenHolder struct {
	mu    sync.RWMutex
	token string // empty string = no token (already consumed or never set)
}

// NewSetupTokenHolder constructs an empty holder. Use Generate() to
// populate it at boot when the users bucket is empty.
func NewSetupTokenHolder() *SetupTokenHolder {
	return &SetupTokenHolder{}
}

// Generate creates a fresh 32-byte hex token, stores it on the
// holder, and returns it for logging. The returned string is the
// exact value that the operator must paste into the /setup form.
//
// Panics on crypto/rand failure: a working entropy source is a
// hard prerequisite for any auth bootstrap; a degraded source
// makes the token guessable and must abort startup.
func (h *SetupTokenHolder) Generate() string {
	buf := make([]byte, SetupTokenByteLen)
	if _, err := rand.Read(buf); err != nil {
		panic("api: crypto/rand failed during setup token generation: " + err.Error())
	}
	tok := hex.EncodeToString(buf)
	h.mu.Lock()
	h.token = tok
	h.mu.Unlock()
	return tok
}

// Verify constant-time compares the supplied candidate against the
// current token. Returns true only if a token is currently set AND
// the candidate matches exactly.
//
// Uses crypto/subtle.ConstantTimeCompare to avoid leaking the
// matching prefix length through timing differences.
func (h *SetupTokenHolder) Verify(candidate string) bool {
	h.mu.RLock()
	current := h.token
	h.mu.RUnlock()
	if current == "" {
		return false
	}
	// ConstantTimeCompare returns 1 if equal, 0 otherwise; it also
	// requires equal-length inputs, otherwise returns 0 directly.
	return subtle.ConstantTimeCompare([]byte(current), []byte(candidate)) == 1
}

// Invalidate clears the token. Called after a successful /auth/setup
// to prevent replay. Idempotent.
func (h *SetupTokenHolder) Invalidate() {
	h.mu.Lock()
	h.token = ""
	h.mu.Unlock()
}

// Active reports whether a token is currently set. Used by the
// /auth/setup handler to short-circuit when the holder has been
// invalidated (e.g., setup already ran in this process).
func (h *SetupTokenHolder) Active() bool {
	h.mu.RLock()
	defer h.mu.RUnlock()
	return h.token != ""
}
