// Arenet - Homelab-friendly reverse proxy with integrated security
// Copyright (C) 2026  Ludovic Ramos
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see https://www.gnu.org/licenses/.

package audit

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	bolt "go.etcd.io/bbolt"
)

// bucketName is the BoltDB bucket where audit events live. It must be
// pre-created by storage.NewStore (see internal/storage/storage.go).
const bucketName = "audit"

// Store persists immutable audit events into the BoltDB "audit" bucket.
// Events are keyed by the 16 raw bytes of their UUID v7, which sorts
// lexicographically in chronological order.
//
// Store is safe for concurrent use: bbolt serializes writes through a
// single-writer transaction model, and reads are MVCC-snapshot.
type Store struct {
	db *bolt.DB
}

// NewStore returns an audit store backed by the given bbolt handle.
// The handle is shared with the rest of the application; the caller
// retains ownership and is responsible for closing it.
func NewStore(db *bolt.DB) *Store {
	if db == nil {
		panic("audit.NewStore: db is nil")
	}
	return &Store{db: db}
}

// Append persists a new event in its own bbolt transaction.
//
// The event's ID and Timestamp are ALWAYS generated by this method,
// overwriting any values the caller may have set. This is intentional:
// audit records must not be backdated or have caller-controlled IDs.
//
// Returns an error if the bucket is missing or the bbolt write fails.
// Per decision D2, callers are expected to log and continue rather
// than propagating audit failures to the user-facing response.
func (s *Store) Append(ctx context.Context, evt Event) error {
	if _, ok := ctx.Deadline(); !ok {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, 5*time.Second)
		defer cancel()
	}

	return s.db.Update(func(tx *bolt.Tx) error {
		return s.AppendTx(tx, evt)
	})
}

// AppendTx is the transactional variant of Append. The caller supplies
// the *bolt.Tx (must be writable) and AppendTx writes within it.
//
// AppendTx always regenerates ID (UUID v7) and Timestamp, even if the
// caller pre-fills these fields. Callers MUST NOT depend on the values
// they pass for these two fields; any pre-filled value is discarded.
// This guarantees that audit records cannot be backdated or have
// caller-controlled IDs, regardless of which variant (Append or
// AppendTx) is used.
//
// Reserved for future atomic patterns (multi-bucket transactions).
// Step D handlers use Append directly.
func (s *Store) AppendTx(tx *bolt.Tx, evt Event) error {
	id, err := uuid.NewV7()
	if err != nil {
		return fmt.Errorf("audit: generate uuid v7: %w", err)
	}
	evt.ID = id.String()
	evt.Timestamp = time.Now().UTC()

	b := tx.Bucket([]byte(bucketName))
	if b == nil {
		return fmt.Errorf("audit: bucket %q missing", bucketName)
	}

	key, err := id.MarshalBinary()
	if err != nil {
		return fmt.Errorf("audit: marshal uuid: %w", err)
	}

	value, err := json.Marshal(evt)
	if err != nil {
		return fmt.Errorf("audit: marshal event: %w", err)
	}

	if err := b.Put(key, value); err != nil {
		return fmt.Errorf("audit: put event: %w", err)
	}
	return nil
}

// List returns events matching the filter, in reverse chronological
// order (most recent first), paginated.
//
// The returned nextCursor is the hyphenated UUID v7 of the last event
// in the returned slice. Pass it back in Filter.Cursor to fetch the
// next page. nextCursor is "" when no more events match.
//
// Filtering by ActorUserID, Action, TargetType, TargetID, From, and To
// is done in memory while iterating: the audit bucket is scanned in
// reverse chronological order and non-matching events are skipped.
// Per spec 3.6 this is acceptable given the expected audit volume.
func (s *Store) List(ctx context.Context, f Filter) ([]Event, string, error) {
	if _, ok := ctx.Deadline(); !ok {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, 5*time.Second)
		defer cancel()
	}

	limit := f.Limit
	if limit <= 0 {
		limit = DefaultLimit
	}
	if limit > MaxLimit {
		limit = MaxLimit
	}

	var startKey []byte
	if f.Cursor != "" {
		cur, err := uuid.Parse(f.Cursor)
		if err != nil {
			return nil, "", fmt.Errorf("audit: invalid cursor: %w", err)
		}
		startKey, err = cur.MarshalBinary()
		if err != nil {
			return nil, "", fmt.Errorf("audit: marshal cursor: %w", err)
		}
	}

	out := make([]Event, 0, limit)

	err := s.db.View(func(tx *bolt.Tx) error {
		b := tx.Bucket([]byte(bucketName))
		if b == nil {
			return fmt.Errorf("audit: bucket %q missing", bucketName)
		}
		c := b.Cursor()

		var k, v []byte
		if startKey != nil {
			// Seek to the cursor position, then move one step back so
			// the next event is strictly older than the cursor.
			k, v = c.Seek(startKey)
			// Seek lands on startKey if present, or on the next key
			// greater than startKey if not. In either case, we want
			// to start from the event strictly before startKey.
			if k != nil {
				k, v = c.Prev()
			} else {
				// Past the end; start from the most recent event.
				k, v = c.Last()
			}
		} else {
			k, v = c.Last()
		}

		for ; k != nil; k, v = c.Prev() {
			var evt Event
			if err := json.Unmarshal(v, &evt); err != nil {
				return fmt.Errorf("audit: unmarshal event %x: %w", k, err)
			}
			if !matches(evt, f) {
				continue
			}
			out = append(out, evt)
			if len(out) >= limit {
				break
			}
		}
		return nil
	})
	if err != nil {
		return nil, "", err
	}

	nextCursor := ""
	if len(out) == limit {
		nextCursor = out[len(out)-1].ID
	}
	return out, nextCursor, nil
}

// QueryByActionRange walks the audit bucket in reverse chronological
// order and returns the events whose Action is in `actions` and whose
// Timestamp falls in [from, to). The walk stops at the first event
// whose Timestamp is before `from`, OR when `limit` events have been
// collected — whichever comes first.
//
// Returns (events, hitCap, error):
//   - events: the matching slice, most-recent first.
//   - hitCap: true when the walk stopped because `limit` was reached
//     before the `from` boundary. The caller uses this to surface a
//     "partial result" flag (Step Q §1.5 — the auth-failures endpoint
//     exposes it to the dashboard).
//   - error: bucket missing / JSON unmarshal failure.
//
// `actions` empty → no action filter (all events in the range). nil
// actions slice is treated the same as empty. `to.IsZero()` → no
// upper bound. `from.IsZero()` → no lower bound (the walk stops only
// when the bucket is exhausted or limit is hit).
//
// limit <= 0 defaults to DefaultLimit; values above MaxLimit are
// clamped silently — same convention as List.
//
// Implementation note: scans the bucket reverse-key, which is also
// reverse chronological thanks to UUID v7 ordering. The action and
// time filters are applied in memory — same trade-off as List(), and
// the Step Q audit-failure volume is in the single-digits-per-minute
// range in normal operation (spec §1.3 D4).
func (s *Store) QueryByActionRange(ctx context.Context, actions []string, from, to time.Time, limit int) ([]Event, bool, error) {
	if _, ok := ctx.Deadline(); !ok {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, 5*time.Second)
		defer cancel()
	}

	if limit <= 0 {
		limit = DefaultLimit
	}
	if limit > MaxLimit {
		limit = MaxLimit
	}

	// Pre-build the action set for O(1) membership test. nil slice
	// = no filter (the empty-set case below short-circuits with
	// "match-all").
	var actionSet map[string]struct{}
	if len(actions) > 0 {
		actionSet = make(map[string]struct{}, len(actions))
		for _, a := range actions {
			actionSet[a] = struct{}{}
		}
	}

	out := make([]Event, 0, limit)
	hitCap := false

	err := s.db.View(func(tx *bolt.Tx) error {
		b := tx.Bucket([]byte(bucketName))
		if b == nil {
			return fmt.Errorf("audit: bucket %q missing", bucketName)
		}
		c := b.Cursor()
		for k, v := c.Last(); k != nil; k, v = c.Prev() {
			var evt Event
			if err := json.Unmarshal(v, &evt); err != nil {
				return fmt.Errorf("audit: unmarshal event %x: %w", k, err)
			}
			// `from` cutoff: events older than `from` end the walk
			// (the bucket is reverse-chronological so everything
			// past this point is also older — short-circuit).
			if !from.IsZero() && evt.Timestamp.Before(from) {
				return nil
			}
			// `to` cutoff: events at-or-after `to` are skipped
			// (but we keep walking — older events may still match).
			if !to.IsZero() && !evt.Timestamp.Before(to) {
				continue
			}
			if actionSet != nil {
				if _, ok := actionSet[evt.Action]; !ok {
					continue
				}
			}
			out = append(out, evt)
			if len(out) >= limit {
				// Cap hit. If there is still at least one older
				// event in the bucket (whether matching or not),
				// the caller is owed a "partial" flag.
				if k2, _ := c.Prev(); k2 != nil {
					hitCap = true
				}
				return nil
			}
		}
		return nil
	})
	if err != nil {
		return nil, false, err
	}
	return out, hitCap, nil
}

// matches returns true if evt satisfies every non-zero field of f.
// Zero values mean "no filter on this field".
func matches(evt Event, f Filter) bool {
	if f.ActorUserID != "" && evt.ActorUserID != f.ActorUserID {
		return false
	}
	if f.Action != "" && evt.Action != f.Action {
		return false
	}
	if f.TargetType != "" && evt.TargetType != f.TargetType {
		return false
	}
	if f.TargetID != "" && evt.TargetID != f.TargetID {
		return false
	}
	if !f.From.IsZero() && evt.Timestamp.Before(f.From) {
		return false
	}
	if !f.To.IsZero() && !evt.Timestamp.Before(f.To) {
		return false
	}
	return true
}
